#!/bin/bash

set -euo pipefail

NCPUS=2

SUBTARGET=mame		# build everything
#SUBTARGET=arcade	# build arcade games

cd ./mame
git fetch
cd -

if [ -z "$1" ]
then
  cd ./mame
  git pull --rebase
  make -j $NCPUS SUBTARGET=$SUBTARGET
  cd -
else
  git-new-workdir ./mame $1
  cd ./$1
  git checkout $1

  # HEAD commit on master adds machine type to -listxml.
  git cherry-pick master

  sed -i "s/^# USE_QTDEBUG = 1/USE_QTDEBUG = 0/" makefile

  if [ -e README.md ]
  then
    set +e
    grep --quiet "SUBTARGET=" README.md
    USE_SUBTARGET=$? # 0=true / 1=false
    set -e
  else
    USE_SUBTARGET=1  # 1=false
  fi

  if [ $USE_SUBTARGET -eq 0 ]
  then
    make -j $NCPUS SUBTARGET=$SUBTARGET
    make clean
  else
    make -j $NCPUS OSD=osdmini
    # 'make clean' used to destroy the binary.
  fi
  cd -
  ./genmeta
  ./gendiff
fi
