#!/bin/bash

set -euo pipefail

NCPUS=2

cd ./mame
git fetch
cd -

if [ -z "$1" ]
then
  cd ./mame
  git pull --rebase
  make -j $NCPUS SUBTARGET=arcade
  cd -
else
  git-new-workdir ./mame $1
  cd ./$1
  git checkout $1
  sed -i "s/^# USE_QTDEBUG = 1/USE_QTDEBUG = 0/" makefile
  grep --quiet "SUBTARGET=arcade" README.md
  if [ $? -eq 0 ]
  then
    make -j $NCPUS SUBTARGET=arcade
    make clean
  else
    make -j $NCPUS
    # 'make clean' used to destroy the binary.
  fi
  cd -
  ./genmeta
  ./gendiff
fi
