#!/bin/bash

set -euo pipefail

PREVTAG=''

for TAG in $(find -maxdepth 1 -type d -name 'mame0*' | sort)
do
  THIS=$(expr "$TAG" : '.*\([[:digit:]]\{4\}\)')
  PREV=$(printf %04d $(expr "$THIS" - 1))

  # Skip the 1st loop iteration.
  if [ ! -z "$PREVTAG" ]
  then
    OUTFILE="dtd-$PREV-$THIS.diff"
    if [ ! -e "$OUTFILE" ]
    then
      # diff exits with 1 if inputs are different.
      set +e
      diff -up \
        <($PREV/mame*64 -listxml | head --lines 200 | sed --quiet '0,/^$/p' | head --lines -1) \
        <($THIS/mame*64 -listxml | head --lines 200 | sed --quiet '0,/^$/p' | head --lines -1) \
        > $OUTFILE
      set -e
    fi

    OUTFILE="usage-$PREV-$THIS.diff"
    if [ ! -e "$OUTFILE" ]
    then
      # diff exits with 1 if inputs are different.
      set +e
      diff -up \
        <($PREV/mame*64 -showusage | grep "^-" | sort) \
        <($THIS/mame*64 -showusage | grep "^-" | sort) \
        > $OUTFILE
      set -e
    fi
  fi

  PREVTAG="$TAG"
done
